### ISSUE TITLE
Feature extractor used for kaggle competition

### ISSUE THREAD

**Issue by wendyli** [sics-lm/kaggle-seizure-prediction#1]
Hi there,

We're using your model to plot performance vs. power costs on gem5-aladdin.  It's been a while since you wrote this, but could you go into more detail about what features you used for your kaggle competition?  Does hills by itself produce the highest AUC or do you use a combination of all three feature extractors?  

Thank you

**Comment by thvasilo** [comment]
Hello @wendyli,

IIRC we ended up only using the Hills features alone. We tried using Wavelets in isolation, or in combination with Hills, but that gave us worse AUC performance. Not sure about the cross-correlation features.
